// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dashboard

import (
	"github.com/iimeta/fastapi/v2/api/dashboard"
)

type ControllerV1 struct{}

func NewV1() dashboard.IDashboardV1 {
	return &ControllerV1{}
}
