// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package audio

import (
	"github.com/iimeta/fastapi/v2/api/audio"
)

type ControllerV1 struct{}

func NewV1() audio.IAudioV1 {
	return &ControllerV1{}
}
