// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package general

import (
	"github.com/iimeta/fastapi/api/general"
)

type ControllerV1 struct{}

func NewV1() general.IGeneralV1 {
	return &ControllerV1{}
}
