// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package volcengine

import (
	"github.com/iimeta/fastapi/v2/api/volcengine"
)

type ControllerV1 struct{}

func NewV1() volcengine.IVolcengineV1 {
	return &ControllerV1{}
}
