// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package video

import (
	"github.com/iimeta/fastapi/api/video"
)

type ControllerV1 struct{}

func NewV1() video.IVideoV1 {
	return &ControllerV1{}
}
