// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package openai

import (
	"github.com/iimeta/fastapi/v2/api/openai"
)

type ControllerV1 struct{}

func NewV1() openai.IOpenaiV1 {
	return &ControllerV1{}
}
