// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package embedding

import (
	"github.com/iimeta/fastapi/api/embedding"
)

type ControllerV1 struct{}

func NewV1() embedding.IEmbeddingV1 {
	return &ControllerV1{}
}
