package dao

const (
	USER           = "user"
	RESELLER       = "reseller"
	APP            = "app"
	APP_KEY        = "app_key"
	PROVIDER       = "provider"
	MODEL          = "model"
	MODEL_AGENT    = "model_agent"
	KEY            = "key"
	GROUP          = "group"
	TASK_VIDEO     = "task_video"
	TASK_FILE      = "task_file"
	TASK_BATCH     = "task_batch"
	LOG_TEXT       = "log_text"
	LOG_IMAGE      = "log_image"
	LOG_AUDIO      = "log_audio"
	LOG_VIDEO      = "log_video"
	LOG_FILE       = "log_file"
	LOG_BATCH      = "log_batch"
	LOG_MIDJOURNEY = "log_midjourney"
	LOG_GENERAL    = "log_general"
	SYS_CONFIG     = "sys_config"
)
