// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package anthropic

import (
	"github.com/iimeta/fastapi/v2/api/anthropic"
)

type ControllerV1 struct{}

func NewV1() anthropic.IAnthropicV1 {
	return &ControllerV1{}
}
