// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package moderation

import (
	"github.com/iimeta/fastapi/v2/api/moderation"
)

type ControllerV1 struct{}

func NewV1() moderation.IModerationV1 {
	return &ControllerV1{}
}
