// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package midjourney

import (
	"github.com/iimeta/fastapi/api/midjourney"
)

type ControllerV1 struct{}

func NewV1() midjourney.IMidjourneyV1 {
	return &ControllerV1{}
}
