// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package google

import (
	"github.com/iimeta/fastapi/v2/api/google"
)

type ControllerV1 struct{}

func NewV1() google.IGoogleV1 {
	return &ControllerV1{}
}
