// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package batch

import (
	"github.com/iimeta/fastapi/v2/api/batch"
)

type ControllerV1 struct{}

func NewV1() batch.IBatchV1 {
	return &ControllerV1{}
}
